name: recce_app
description: A simple recce Flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
